name: docker_image

on:
  push:
  pull_request:

jobs:
  push_dev_image_harbor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: harbor.stfc.ac.uk
          username: ${{ secrets.HARBOR_DEV_USERNAME }}
          password: ${{ secrets.HARBOR_DEV_TOKEN }}

      - name: Set commit SHA for later
        id: commit_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Horizon and push to staging
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: "harbor.stfc.ac.uk/stfc-cloud-staging/openstack-horizon:${{ steps.commit_sha.outputs.sha_short }}"

      - name: Inform of tagged name
        run: echo "Image published to harbor.stfc.ac.uk/stfc-cloud-staging/openstack-horizon:${{ steps.commit_sha.outputs.sha_short }}"

  push_prod_image_harbor:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: harbor.stfc.ac.uk
          username: ${{ secrets.HARBOR_PROD_USERNAME }}
          password: ${{ secrets.HARBOR__PROD_TOKEN }}

      - name: Get release tag for later
        id: release_tag
        run: echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT

      - name: Check if release file has updated
        uses: dorny/paths-filter@v2
        id: release_updated
        with:
          filters: |
            version:
              - 'version.txt'

      - name: Build Horizon and push to prod
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "harbor.stfc.ac.uk/stfc-cloud/openstack-horizon:v${{ steps.release_tag.outputs.version }}"

      - name: Inform of tagged name
        if: steps.release_updated.outputs.version == 'true'
        run: echo "Image published to harbor.stfc.ac.uk/stfc-cloud/openstack-horizon:v${{ steps.release_tag.outputs.version }}"
